### ISSUE TITLE
论坛指南

### ISSUE THREAD

**Issue by shyfcka** [box3-blockly/form#1]
# 欢迎
欢迎来到论坛， 此贴将介绍一些实用技巧

## 如何查看帖子
首先打开github， 然后在左上角搜索`box3-blockly/form`然后选择有中文描述的那个就可以进入论坛首页
进入首页后， 点击上面（浅蓝色背景）的`issues`选项卡，就可以进入论坛列表
为了方便起见，建议将下面的网址添加到浏览器收藏（点击浏览器地址栏右边的星星图标）
`https://github.com/box3-blockly/form/issues`
### 帖子索引表
为了方便大家快速找到官方帖和优质帖子, 我们特别加入了索引表帖, 位于论坛首页上方的卡片中(`Pinned issues`下面)
索引表中包含一些链接, 可以直接点击并浏览相应帖子

### 每周精华帖
管理员将在每周评选精华帖, 每次评选2个, 将在论坛首页与索引表平齐的位置展示一周
 
### 返回帖子列表
点击页面上浅蓝色区域的`Issues`选项卡即可, 如果你添加了浏览器书签, 也可以直接点击书签进入
## 如何发布帖子
首先回到论坛列表, 点击右上角的绿色`New Issue`按钮,然后选择一个模版（点击模版右边对应的绿色按钮即可选择）, 就可以进入发帖页面
在发帖页面中, 左边是编辑区域, 上面的长条输入框(默认内容是`Title`)是标题, 下面的`Write` 是编辑模式, 可以编写内容, 旁边的`Preview` 是预览, 用来预览你的帖子
在编写正文的时候, 可以使用上方的工具来进行排版, 也可以使用markdown语法([点击查看教程](https://www.runoob.com/markdown/md-title.html)) 
编写完成后, 可以在右边的`Labels`中为你的帖子添加标签
万事具备后, 在编辑框的右下角点击`Submit new issue`即可发布

### 发帖的注意事项
- 为了大家的体验, 请勿使用与帖子无关的标签, 如果发现, 则删除对应标签, 严重者删帖
- 如果帖子中存在错别字, 或者想要修改, 你可以打开自己的帖子, 然后在帖子正文右上角的`...`中选择`Edit`即可重新编辑
- 如果你要发送一个问题反馈帖(判断依据为带有特定标签), 请根据发帖指南(之后补上)的格式发帖, 示例: #2 
# 感谢
如果你喜欢并支持`box3-blockly`团队, 那么请分享下面的链接, 让更多人知道这个论坛!
[](https://github.com/box3-blockly/form/issues)
\***长期更新, 未完待续**\*

**Comment by baka-prog** [comment]
ohhhhhh

**Comment by 86135** [comment]
有一个问题是怎么加标签？只有您有权限加吧
